### ISSUE TITLE
Module not loading 

### ISSUE THREAD

**Issue by PaziLee26** [daniel-windsor/MMM-eswordoftheday#6]
When code is inserted, I called it out on config.js file, and there is just a dot with no words. Are you able to help me troubleshoot? 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/122642316/212435479-945283f2-f5b0-44b4-aac7-0c9731632319.png)

**Comment by benjf** [comment]
I got this working by checking out one commit prior to the latest...
`git checkout 7db81145a2e238f2400fa2e82407a9078790048c`
`npm install`
restart MagicMirror

**Comment by BerkSmash1984** [comment]
This worked for me too

**Comment by devtobi** [comment]
@benjf This does not work anymore. Maybe the API changed or something?

**Comment by benjf** [comment]
Mine has also stopped working. I think this module is just scraping the page (not using an API), so my guess is that spanishdict updated their design/markup.

**Comment by BerkSmash1984** [comment]
Same here. I don't see any errors related to an API failing in the dev console so it does appear to simply be scraping. I disabled the module on my MM for now...

**Comment by devtobi** [comment]
Yeah you are right, the IDs in the html page are not just some random IDs. I could fork this module and adjust the scraping code accordingly. But we never know long it stays compatible with the official page.

EDIT: My solution would be to introduce configuration parameters for the 4 fields, so the module can easily be adjusted when just the class names change.

**Comment by daniel-windsor** [comment]
Hey @benjf , @BerkSmash1984 , @devtobi 

Thanks for the bug report, it seems the website was updated and the scraper broke :(  I've pushed an update which should fix it for now.  

I might have a think about moving to a different source where I can use a proper API, though it would require all users to have their own API key.  If it keeps breaking that may be the lesser of two evils.

**Comment by devtobi** [comment]
@daniel-windsor Thank you for that fast reaction! I just tried it out, and it works like a charm again! I can now start learning Spanish on my mirror. 😃 Thank you very much!

**Comment by BerkSmash1984** [comment]
Working for me now too. Thanks @daniel-windsor!

**Comment by bigrjsuto** [comment]
Hi. I've been experiencing the same issue. I tried updating the module and restarting MM but it's still not displaying a word. Any suggestions?

**Comment by papapep514** [comment]
same here, any pointers?

**Comment by BerkSmash1984** [comment]
Mine was still working as of yesterday (out of town currently). The owner of the website may have made another change that is preventing the scraping of the website data
